name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate activity metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: JABaker99
          template: classic
          base: header, activity
          filename: metrics-activity.svg
          output_action: commit

      - name: Languages activity (usage-focused)
        uses: lowlighter/metrics@master
        with:
          filename: metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JABaker99
      
          base: ""
          plugin_languages: yes

          #Adding Assembly Project that are ignored without
          plugin_languages_indepth_custom: >-
            Commodore-64-Character-Classifier-And-Screen-Output-Program,
            Commodore-64-Text-Output-Demo,
            Commodore-64-Multi-Sprite-Ghost,
            C64-Cat-And-Mushroom-Sprite-Game,
            C64-Animated-Sprite-Eye,
            IPv6-Converter-And-Endianess-Utility

          plugin_languages_details: lines, percentage
          plugin_languages_limit: 20
          plugin_languages_threshold: 0%
          plugin_languages_other: no
          plugin_languages_sections: most-used
      
          repositories_affiliations: owner,collaborator,organization_member
          repositories_forks: yes
      
          plugin_languages_ignored: >-
            json,yaml,yml,xml,md,txt,ini,
            dockerfile,makefile,cmake,
            gradle,gitignore,scss,css,html
      
          plugin_languages_aliases: >-
            C#:C#,CSharp,.NET,ASP.NET
            Python:Python
            C++:C++,CPP
            Assembly:Assembly,ASM,6502 Assembly

          extras_css: |
            .languages .title,
            .languages .count {
              display: none !important;
            }
            .languages .section-title {
              font-size: 20px !important;
              font-weight: 600 !important;
            }
            .languages .language text {
              font-size: 14px !important;
            }
      
          delay: 120
          output_action: commit
          plugins_errors_fatal: yes

