name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate activity metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: JABaker99
          template: classic
          base: header, activity
          filename: metrics-activity.svg
          output_action: commit

      - name: Generate language metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: JABaker99
          template: classic
          base: ""

          
          plugin_languages: yes
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 365
          plugin_languages_limit: 10
          plugin_languages_details: percentage
          plugin_languages_other: yes
          plugin_languages_categories: programming,markup
          
          filename: metrics-languages.svg
          output_action: commit
