name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate activity metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: JABaker99
          template: classic
          base: header, activity
          filename: metrics-activity.svg
          output_action: commit

      - name: Language activity (Most used Languages)
        uses: lowlighter/metrics@master
        with:
          filename: metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JABaker99
      
          base: ""
          plugin_languages: yes
          
          # SHOW EVERYTHING
          plugin_languages_limit: 50
          plugin_languages_threshold: 0%
          plugin_languages_other: no
          plugin_languages_details: bytes-size, percentage
      
          # SHOW BOTH VIEWS
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 365
      
          # DEEP SCAN
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
      
          delay: 120
          output_action: commit
          plugins_errors_fatal: yes

